---
on:
  pull_request:
  merge_group:

jobs:
  pre-commit:
    name: "pre-commit"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: "Do not ignore pre-commit failures on PRs"
        if: github.event_name != 'merge_group'
        run: echo "IGNORE_FAILURE=false" >> $GITHUB_ENV
        shell: bash
      - name: "Ignore pre-commit failures on gh merge queues"
        if: github.event_name == 'merge_group'
        run: echo "IGNORE_FAILURE=true" >> $GITHUB_ENV
        shell: bash
      - uses: SonarSource/gh-action_pre-commit@3d5b503c1ce51d0f92665875b9bea716eff1e70f # 1.0.7
        with:
          extra-args: --from-ref=origin/${{ github.event.pull_request.base.ref }} --to-ref=${{ github.event.pull_request.head.sha }}
          ignore-failure: ${{ env.IGNORE_FAILURE }}

